        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 13 16:14:28 2016
        MODULE READSTATS__genmod
          INTERFACE 
            SUBROUTINE READSTATS
            END SUBROUTINE READSTATS
          END INTERFACE 
        END MODULE READSTATS__genmod
