        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 13 16:14:28 2016
        MODULE WRITESTATS__genmod
          INTERFACE 
            SUBROUTINE WRITESTATS
            END SUBROUTINE WRITESTATS
          END INTERFACE 
        END MODULE WRITESTATS__genmod
